---
title: 'Analyzing_Florida_whole_state'
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# read in data
```{r}
florida_csv <- read.csv("~/Documents/work/Spacial_adj/Florida_whole_state2014dm2.csv", header = TRUE)
florida_8_3 <- read.csv("~/Documents/work/Spacial_adj/Florida_8_3_2014dm2.csv", header = TRUE)
florida_8_5 <- read.csv("~/Documents/work/Spacial_adj/Florida_8_5_2014dm2.csv", header = TRUE)
  
oregon_6_2 <- read.csv("~/Documents/work/Spacial_adj/Oregon_6_2_2014dm2.csv", header = TRUE)
oregon_7_1 <-  read.csv("~/Documents/work/Spacial_adj/Oregon_7_1_2014dm2.csv", header = TRUE)
```
# Helper functions
```{r, echo=FALSE}

upper_bound_ratios <- function(x){
  upper <- rep(NA, length(x))
  edge <- rep(NA, length(x))
  interior <- rep(NA, length(x))
  ## get edges
  for(i in seq_along(x)){
    smaller_sqrt <- floor(sqrt(x[i]))
    smaller_square <- smaller_sqrt^2
    
    larger_sqrt <- ceiling(sqrt(x[i]))
    
    remainder <- x[i] %% smaller_square
    
    if (remainder > smaller_sqrt){
      edge[i] <- 4 * larger_sqrt
    }
    
    if (remainder <= smaller_sqrt){
      edge[i] <- (2*smaller_sqrt) + 2*(1+smaller_sqrt)
    }
    
    if (remainder == 0){
      edge[i] <- 4 * larger_sqrt
    }
  }
  
  #get interiors
  for (i in seq_along(x)){
    interior[i] <- 4 * x[i]
    interior[i] <- interior[i] - edge[i]
  }
  
  for (i in seq_along(x)){
    if (x[i] == 1){
      upper[i] <- 0
      next  
    }
    if (x[i] == 2){
      upper[i] <- 0.25
      next
    }
    if (x[i] == 3){
      upper[i] <- 0.5
      next 
    }
    
    upper[i] <- interior[i] / (interior[i] + edge[i])
  }
  
  
  return(upper)
}

lower_bound_ratios <- function(x){
  lower <- rep(NA, length(x))
  edge <- rep(NA, length(x))
  interior <- rep(NA, length(x))
  
  for (i in seq_along(x)){
    if(x[i] == 1){
      edge[i] <- 4
      next
    }
    
    if (x[i] == 2){
      edge[i] <- 6  
      next
    }
    
      edge[i] <- (2 * (x[i] - 2)) + 6 # The six accounts for the two end pixels 
  }
  
  for (i in seq_along(x)){
    if(x[i] == 1){
    interior[i] <- 0
     lower[i] <- interior[i] / (interior[i] + edge[i])
      next
    }
    
    if (x[i] == 2){
     interior[i] <- 2
      lower[i] <- interior[i] / (interior[i] + edge[i])
      next
    }
    
     interior[i] <- ((4 * x[i]) - edge[i])
     lower[i] <- interior[i] / (interior[i] + edge[i])
  }
  return (lower)
}

seq <- c(1:length(florida_csv$sizw))
lower <- lower_bound_ratios(seq)
upper <- upper_bound_ratios(seq)

```

#Sifting out edge-case with artificial ratio inflation, and filling in missing names
```{r}
oregon_6_2$eco_II <- "6.2"
oregon_7_1$eco_II <- "7.1"
florida_8_3$eco_II <- "8.3"
florida_8_5$eco_II <- "8.5"

florida <- rbind(florida_8_3, florida_8_5)
oregon <- rbind(oregon_6_2, oregon_7_1)

florida$size_ha <- florida$sizw * 0.003
oregon$size_ha <- oregon$sizw * 0.003

florida$state <- "FL"
oregon$state <- "OR"
final <- rbind(florida, oregon)


final$ratio[(final$ratio > 0.25) & (final$sizw == 2)] <- NA
final$ratio[(final$ratio > 0.33) & (final$sizw == 3)] <- NA
final$ratio[(final$ratio > 0.50) & (final$sizw == 4)] <- NA
final$ratio[(final$ratio > 0.5 ) & (final$sizw == 5)] <- NA
final$ratio[(final$ratio > 0.55333333) & (final$sizw == 6)] <- NA
final$ratio[(final$ratio > 0.5714286) & (final$sizw == 7)] <- NA
final$ratio[(final$ratio >  0.7083333) & (final$sizw == 12)] <- NA
final$ratio[(final$ratio >  0.7631579) & (final$sizw == 19)] <- NA

## Add in dist names from 2014 lables -only strange unknown case

disturbence_csv <- read.csv("~/Downloads/Disturbance1999-2014/disturb2014.csv", header = TRUE)


```

Get ratio file for testing. Double check ani-joins. 
```{r}

unknowns <- final[grep("Unknown", final$dist_name) ,]  ## Note, this filetering discriminates against large disturbences, which tend to have large sections of known ID's but some small unknowns mixed in. Better to seperate out just "Unknown" and leave "Wildfire, unknown?"
no_unknowns <- dplyr::anti_join(final, unknowns, by = "dist_name") 

mixed_disturbence <- final[grep(",", final$dist_name), ]
single_disturbence <- dplyr::anti_join(final, mixed_disturbence, by = "dist_name")

length(mixed_disturbence$dist_name)/ length(final$dist_name)

#mixed_with_just_unknows <- dplyr::anti_join(mixed_disturbence, no_unknowns, by = "dist_name")

no_unknowns_mixed_disturbence <- dplyr::anti_join(mixed_disturbence, unknowns, by = "dist_name") 
no_unknowns_single_disturbence <- dplyr::anti_join(single_disturbence, unknowns, by = "dist_name")

```



Estimate qa/qc stats
```{r}
## overall size ratios
library(lemon)
library(knitr)

## Estimate unknown disturbence
table <- list()
table$percent_unknown_disturbence_event <- dim(unknowns)[1]/dim(final)[1]
table$pecent_mixed_disturbence_event <- dim(mixed_disturbence)[1] /dim(final)[1]
table$percent_unknown_area <- sum(unknowns$size_ha) / sum(final$size_ha)
table$pecent_mixed_disturbence_area <- sum(mixed_disturbence$size_ha) / sum(final$size_ha)
table$percent_mixed_no_unknows <- sum(no_unknowns_mixed_disturbence$size_ha)/ sum(final$size_ha)
print(table)



```



#Hex plots

```{r}
# Density plot for data overall. Lets us see data rich vs data poor areas. 


library(dplyr)
library(ggplot2)


seq <- c(1:length(oregon$sizw))
seq[length(seq)] <- max(oregon$sizw)
lower <- lower_bound_ratios(seq)
upper <- upper_bound_ratios(seq)

ggplot(oregon, aes(sizw, ratio), show.legend = TRUE) +
  geom_hex() + 
  scale_fill_gradient(trans = "log")+
  geom_line(aes(x =seq , y = upper), color = "black")+
  geom_line(aes(x =seq , y = lower), color = "black")+
  geom_density_2d(color = "dark green") + 
  scale_x_continuous(trans="log") 

seq <- c(1:length(florida$sizw))
seq[length(seq)] <- max(florida$sizw)
lower <- lower_bound_ratios(seq)
upper <- upper_bound_ratios(seq)

ggplot(florida, aes(size_ha, ratio), show.legend = TRUE) +
  geom_hex() + 
  geom_line(aes(x =seq * 0.003 , y = (upper )), color = "black")+
  geom_line(aes(x =seq * 0.003 , y = (lower )), color = "black")+
   geom_density_2d(color = "dark green")+ 
  scale_x_continuous(trans="log") +
  scale_fill_gradient(trans = "log")


ggplot(florida, aes(size_ha, ratio), show.legend = TRUE) +
  geom_hex() + 
  geom_line(aes(x =seq * 0.003 , y = (upper )), color = "black")+
  geom_line(aes(x =seq * 0.003 , y = (lower )), color = "black")+
   geom_density_2d(color = "dark green")+ 
  scale_x_continuous(trans="log") +
  scale_fill_gradient(trans = "log") + 
  xlab("Area ha") +
  ylab("Edge to Interior Ratio")

ggplot(florida, aes(x = size_ha)) +
  geom_density( fill = "light blue") +
  xlab("Area ha") +
scale_x_continuous(trans="log")
 
  

```

#Different disturbence types

```{r, echo= TRUE}

fire_only <- single_disturbence[grep("ire", single_disturbence$dist_name),]
wildland <- fire_only[grep("Wildland", fire_only$dist_name),]
wildfire <- fire_only[grep("Wildfire", fire_only$dist_name),]
Prescribed <- fire_only[grep("Prescribed Fire", fire_only$dist_name),]


clearcut_only <- single_disturbence[grep("Clear", single_disturbence$dist_name),]
herbicide_only <- single_disturbence[grep("Herbicide", single_disturbence$dist_name),]
thining_only <- single_disturbence[grep("Thinning", single_disturbence$dist_name),]
other_mechanical <- single_disturbence[grep("Other Mechanical", single_disturbence$dist_name),]

## Removeing single, double , and triple pixels
fire_only <- fire_only[fire_only$sizw != 1 & fire_only$sizw !=2 & fire_only$sizw !=3,]
clearcut_only <- clearcut_only[clearcut_only$sizw != 1 & clearcut_only$sizw !=2 & clearcut_only$sizw !=3,]
wildland <- wildland[wildland$sizw != 1 & wildland$sizw !=2 & wildland$sizw !=3,]
prescibed <- Prescribed[Prescribed$sizw != 1 & Prescribed$sizw !=2 & Prescribed$sizw !=3,]
wildfire <- wildfire[wildfire$sizw != 1 & wildfire$sizw !=2 & wildfire$sizw !=3,]
thining_only <- thining_only[thining_only$sizw != 1 & thining_only$sizw !=2 & thining_only$sizw !=3,]
other_mechanical <- other_mechanical[other_mechanical$sizw != 1 & other_mechanical$sizw !=2 & other_mechanical$sizw !=3,]

dists <- c(clearcut_only, wildland, wildfire, prescibed, thining_only, other_mechanical)
```

# KS tests and Density plots

```{r, echo=TRUE}
ggplot(final, aes(x = size_ha)) +
  geom_density( fill = "light blue") +
  xlab("Area ha") +
scale_x_continuous(trans="log")

final %>%
  filter(final$state == "OR") %>%
ggplot( aes(x = size_ha)) +
  geom_density( fill = "light blue") +
  xlab("Area ha") +
scale_x_continuous(trans="log")
final %>%
  filter(final$state == "FL") %>%
ggplot( aes(x = size_ha)) +
  geom_density( fill = "light blue") +
  xlab("Area ha") +
scale_x_continuous(trans="log")

ggplot(fire_only, aes(x = size_ha)) +
  geom_density( fill = "light blue") +
  geom_density(data= wildland, aes(x = size_ha),fill = "dark blue", position = "stack") +
  geom_density(data = wildfire, aes(x = size_ha), fill = "blue", position = "stack")+ 
  xlab("Area ha") +
scale_x_continuous(trans="log") 

ggplot(fire_only, aes(x = size_ha)) +
  geom_density( fill = "light blue") +
  geom_density(data= wildland, aes(x = size_ha),fill = "dark blue", position = "stack") +
  geom_density(data = wildfire, aes(x = size_ha), fill = "blue", position = "stack")+ 
  xlab("Area ha") +
scale_x_continuous(trans="log") 
  
dist_size<-list(clearcut_only$sizw, wildland$sizw, wildfire$sizw, prescibed$sizw, thining_only$sizw, other_mechanical$sizw)
names(dist_size) <- c("clearcut_only", "wildland", "wildfire", "prescibed", "thining_only","other_mechanical" )

size_dist_resulsts <- list()

#size_dist_resulsts$p_val <- rep(NA, length(dist_size)^2)
#size_dist_resulsts$D_val <-  rep(NA, length(dist_size)^2)
iterator <- 0
for ( i in 1:6){
  for (j in 1:6){
    iterator <- iterator + 1
    results <- ks.test(dist_size[[i]],dist_size[[j]], alternative = "two.sided")
    results$names <- paste(names(dist_size)[i], "x", names(dist_size)[j])
    size_dist_resulsts[[iterator]] <- results
  }
}
 
sig <- rep(NA, 6^2)
for (i in 1:(6^2)){
  
  if(size_dist_resulsts[[i]]$p.value < 0.00131579) { # post Bonferoni correction alpha value (0.05/ 38)
   sig[i] <- paste(size_dist_resulsts[[i]]$names)
  }
    
}

ks.test(dist_size[,2], dist_size[,3], alternative = "two.sided")





```

## Archive plots
```{r}

#fire_mixes <- mixed_disturbence[grep("ire",mixed_disturbence$dist_name),]
fire_only <- single_disturbence[grep("ire", single_disturbence$dist_name),]
wildland <- fire_only[grep("Wildland", fire_only$dist_name),]
wildfire <- fire_only[grep("Wildfire", fire_only$dist_name),]
Prescribed <- fire_only[grep("Prescribed Fire", fire_only$dist_name),]


clearcut_only <- single_disturbence[grep("Clear", single_disturbence$dist_name),]
herbicide_only <- single_disturbence[grep("Herbicide", single_disturbence$dist_name),]
thining_only <- single_disturbence[grep("Thinning", single_disturbence$dist_name),]
other_mechanical <- single_disturbence[grep("Other Mechanical", single_disturbence$dist_name),]
require(ggplot2)
ggplot() +                    
  #geom_point(aes(y=fire_only$ratio, x=fire_only$sizw), colour="red") +  
  geom_point(aes(y=wildland$ratio, x=wildland$sizw), color = "brown")+
  geom_point(aes(y=wildfire$ratio, x=wildfire$sizw), color = "orange")+
  geom_point(aes(y=Prescribed$ratio, x=Prescribed$sizw), color = "yellow")+
  geom_point(aes(y=clearcut_only$ratio, x= clearcut_only$sizw), colour="black")+
  geom_point(aes(y=herbicide_only$ratio, x=herbicide_only$sizw), color ="green")+
  geom_point(aes(y=other_mechanical$ratio, x=other_mechanical$sizw), color = "grey")+
  geom_point(aes(y=thining_only$ratio, x=thining_only$sizw), color = "blue")
  

ggplot() +                    
  #geom_point(aes(y=fire_only$ratio, x=fire_only$sizw), colour="red") +  
  geom_point(aes(y=wildland$ratio, x=wildland$sizw), color = "brown")+
  geom_point(aes(y=wildfire$ratio, x=wildfire$sizw), color = "orange")+
  geom_point(aes(y=Prescribed$ratio, x=Prescribed$sizw), color = "yellow")+
  geom_point(aes(y=clearcut_only$ratio, x= clearcut_only$sizw), colour="black")+
  geom_point(aes(y=herbicide_only$ratio, x=herbicide_only$sizw), color ="green")+
  geom_point(aes(y=other_mechanical$ratio, x=other_mechanical$sizw), color = "grey")+
  geom_point(aes(y=thining_only$ratio, x=thining_only$sizw), color = "blue")+
  xlim(0,1000)#

ggplot() +                    
  #geom_point(aes(y=fire_only$ratio, x=fire_only$sizw), colour="red") +  
  geom_point(aes(y=wildland$ratio, x=wildland$sizw), color = "brown")+
  geom_point(aes(y=wildfire$ratio, x=wildfire$sizw), color = "orange")+
  geom_point(aes(y=Prescribed$ratio, x=Prescribed$sizw), color = "yellow")+
  geom_point(aes(y=clearcut_only$ratio, x= clearcut_only$sizw), colour="black")+
  geom_point(aes(y=herbicide_only$ratio, x=herbicide_only$sizw), color ="green")+
  geom_point(aes(y=other_mechanical$ratio, x=other_mechanical$sizw), color = "grey")+
  geom_point(aes(y=thining_only$ratio, x=thining_only$sizw), color = "blue")+
  xlim(0,100)#


fire_log <- fire_only
fire_log$sizw <- log10(fire_log$sizw) 
ggplot()+
geom_point(aes(y=fire_log$ratio, x=fire_log$sizw), colour="red")

ggplot()+
geom_point(aes(y=florida_8_3$ratio, x=log(florida_8_3$sizw)), color = "blue")+
geom_point(aes(y=florida_8_5$ratio, x=log(florida_8_5$sizw)), color = "red")

no_ones_or_twos <- florida_csv[florida_csv$sizw > 3,]

combined_metrics <- rep(NA, length(florida_csv$sizw))

for (i in seq_along(florida_csv$sizw)){
  combined_metrics[i] <- paste(florida_csv$ratio[i], florida_csv$sizw[i])
}
florida_csv$combined_metrics <- combined_metrics
```






