---
title: "Untitled"
author: "Tempest McCabe"
date: "10/20/2018"
output: html_document
---

```{r}
#library(truncnorm)

### Stealing Lab 7'd definition of a truncated normal distribution 

#dtnorm <- function(x,mu,sd, upper, lower){ # Aleready in Log domain. 
#  y = dnorm(x,mu,sd,log=TRUE)-log(pnorm(upper,mu,sd)-pnorm(lower,mu,sd))
#  y[x< lower | x > upper] = -Inf #I'm truncating the wrong varible
#  return(y)
#}

#dtnorm <- function(x,mu,sd){
#  y = dnorm(x,mu,sd,log=TRUE)-log(pnorm(1,mu,sd)-pnorm(0,mu,sd))
#  y[x<0 | x > 1] = -Inf
#  return(y)
#}
#xseq = seq(-0.5,1,length=100)
#plot(xseq,exp(dtnorm(xseq,0.25,0.3,1, 0)),type='l')
#lines(xseq,dnorm(xseq,0.25,0.3),col=2)

#slope <- 1 # IC
#sd <- 1 # IC
#intercept <- 1 #IC
#param <- c(intercept, slope, sd)
#ratio_probability_size_given <- function (param) {
#  -sum(  dtnorm(fire_only$ratio, (param[1] + param[2]*fire_only$sizw), param[3], #upper_bound_ratios(fire_only$sizw), lower_bound_ratios(fire_only$sizw)))
#}

#test <- nlm(ratio_probability_size_given,c(0.00001, 0.00001, 0.00001)) #Doesn't work super well
#param <- c(0.5, 1)
#opt <- optim(param, ratio_probability_size_given, method="L-BFGS-B")

```

## Trying modifide code from lab 9

```{r, echo= TRUE}
#test_dataset <- na.omit(wildfire)

#ic   <- c(2,2,2) ## initial guess
#beta <- c(0.002,0.0002,0.002)
#LnL  <- function(beta){  ## define likelihood
#  -sum(dbinom(test_dataset$ratio,beta[1] + beta[2]*test_dataset$sizw,beta[3], log = TRUE))
#}
#test <- LnL(ic) ## verify likelihood function works
#PR2  <- nlm(LnL,ic) ## maximize the likelihood
#PR2

test_dataset <- na.omit(wildfire)

ic   <- c(10,1,0.1) ## initial guess
#beta <- c(0.002,0.0002,0.002)
MMLnL  <- function(beta){  ## define likelihood
  LL = -sum(dnorm(test_dataset$ratio,(beta[2]*test_dataset$sizw)/(beta[1]+test_dataset$sizw),beta[3], log = TRUE))
  print(LL)
  if(!is.finite(LL)) return(1000)
  return(LL)
}
test <- MMLnL(ic) ## verify likelihood function works
#PR2  <- nlm(LnL,ic) ## maximize the likelihood
PR2  <- optim(ic,MMLnL,method="L-BFGS-B",upper=c(1000,1,1),lower=c(0,0,0)) ## maximize the likelihood
PR2

MMLnL0  <- function(beta){  ## define likelihood
  LL = -sum(dnorm(test_dataset$ratio,(test_dataset$sizw)/(beta[1]+test_dataset$sizw),beta[2], log = TRUE))
  print(LL)
  if(!is.finite(LL)) return(1000)
  return(LL)
}
ic0=c(10,1)
PR0  <- optim(ic,MMLnL0,method="L-BFGS-B",upper=c(1000,1),lower=c(0,0)) ## 

ic <- c(1, 0.0000000008, 2)
monoLnL <- function(beta){  ## define likelihood
  LL = -sum(dnorm(test_dataset$ratio, beta[1]*(1- exp(-beta[2]*test_dataset$sizw)), beta[3], log = TRUE))
  print(LL)
  if(!is.finite(LL)) return(1000)
  return(LL)
}

test <- monoLnL(ic)
PRmono  <- optim(ic,monoLnL,method="L-BFGS-B")

ic=c(10,1,2,1)
MMLnLpower  <- function(beta){  ## define likelihood
  LL = -sum(dnorm(test_dataset$ratio,(beta[2]*test_dataset$sizw^beta[3])/(beta[1]+test_dataset$sizw^beta[3]),beta[4], log = TRUE))
  print(LL)
  if(!is.finite(LL)) return(1000)
  return(LL)
}
PRMMpower  <- optim(ic,MMLnLpower,method="L-BFGS-B") ## 

ic=c(4,1,2,1)
hollingIV  <- function(beta){  ## define likelihood
  LL = -sum(dnorm(test_dataset$ratio,(beta[2]*test_dataset$sizw^2)/(beta[1]+beta[3]*test_dataset$sizw+ test_dataset$sizw^2),beta[4], log = TRUE))
  print(LL)
  if(!is.finite(LL)) return(1000)
  return(LL)
}
PRhollingIV  <- optim(ic,hollingIV,method="L-BFGS-B",upper=c(1000,1),lower=c(0,0)) ## 

ic=c(400,1,1,1)
tess  <- function(beta){  ## define likelihood
  LL = -sum(dnorm(test_dataset$ratio,(beta[2]*test_dataset$sizw^beta[3])/(beta[1]^(beta[3]-1)+test_dataset$sizw^beta[3]),beta[4], log = TRUE))
  print(LL)
  if(!is.finite(LL)) return(1000)
  return(LL)
}
tess_power  <- optim(ic,tess,method="L-BFGS-B",upper=c(1000,1),lower=c(0,0)) ##


pseq = seq(log10(4),log(max(test_dataset$sizw)),length=1000)
xseq = 10^pseq

plot(test_dataset$sizw,test_dataset$ratio,log='x')
#lines(xseq,(ic[2]*xseq)/(ic[1]+xseq))
beta = PR2$par
lines(xseq,(beta[2]*xseq)/(beta[1]+xseq),col="red")
beta0 = PR0$par
lines(xseq,(xseq)/(beta[1]+xseq),col="green")
lines(xseq, (PRmono$par[1]*(1-exp(-PRmono$par[2]*xseq))), col = "blue")
lines(xseq,(PRMMpower$par[2]*(xseq^PRMMpower$par[3]))/(PRMMpower$par[1]+(xseq^PRMMpower$par[3])),col="orange")
lines(xseq, (tess_power$par[2]*xseq^tess_power$par[3])/((tess_power$par[1]^(tess_power$par[3] -1)) + xseq^tess_power$par[3]))
lines(xseq, (PRhollingIV$par[2]*xseq^2/(PRhollingIV$par[1] + PRhollingIV$par[3]*xseq + xseq^2)) , col = "grey")


```


# using glm function
```{r}
PR1 <- glm(final$ratio ~ final$sizw, family=binomial(link="cauchit"))

plot(PR1$model$`final$sizw`, PR1$model$`final$ratio`, xlim = c(0, 1000))
lines(PR1$model$`final$sizw`, PR1$fitted.values, type = "p", col = "red", xlim = c(0, 1000))
lines(sort(PR1$model$`final$sizw`),sort((PR1$fitted.values/0.03571)*test[2]), col = "red")
lines(sort(PR1$model$`final$sizw`),sort((PR1$fitted.values/0.03571)*test[4]), col = "blue")


library(MASS)

test <- confint(lm)
```
