---
title: "Level II ecoregions"
output: html_notebook
---

Where I play with the level II ecoregion data

```{r}
library(maptools)
require(raster)
require(igraph)

eco_II<-readShapePoly(fn = "~/Documents/work/na_cec_eco_l2/NA_CEC_Eco_Level2.shp")

plot(eco_II)
Southern_coastal_plains <- eco_II[eco_II$NA_L2NAME == "MISSISSIPPI ALLUVIAL AND SOUTHEAST USA COASTAL PLAINS", ]
Southern_coastal_plains$Shape_Area

#flist <- list.files("~/Downloads/LANDFIRE/Southeast/")

#file_path <- paste("~/Downloads/LANDFIRE/Southeast/",flist[1],"/US_DIST2013\\US_DIST2013.tif", sep ="")

#file_path_1 <- paste("~/Downloads/LANDFIRE/Southeast/",flist[2],"/US_DIST2013\\US_DIST2013.tif", sep ="")
#entire_us_1 <- raster(file_path)
#entire_us_2 <- raster(file_path_1)

csv <- read.csv("/Users/tess/Downloads/LANDFIRE/US_DIST2000/CSV_Data/US_disturb2000.csv")

#plot(entire_us_2)
#test1 <- merge(entire_us_1, entire_us_2)
```


Testing Entire US raster file even though it's in a .adf form

```{r}

library(rgdal)

#all_us <- rgdal::readGDAL(fname = "~/Downloads/LANDFIRE/US_DIST2000/grid1/us_dist2000/") # Too big to load locally

tiny_adf <- rgdal::readGDAL(fname = "~/Downloads/LANDFIRE/HI_Dist2011/Grid/hi_dist2011/") 

test_florida_tif <- rgdal::readGDAL(fname = "~/Downloads/LANDFIRE/croped_florida.tif") 
test_florida_tif <- raster(test_florida_tif)

csv<-read.csv("/Users/tess/Downloads/LANDFIRE/US_DIST2000/CSV_Data/US_disturb2000.csv")
tiny_adf <- raster(tiny_adf)
#HI_ratios <- get_ratio_dist(tiny_adf, date="2011", csv = csv)

plot(tiny_adf)

### Crop by an ecoregion



state <- getData("GADM", country="USA", level=1)
mystates <- c("Hawaii")
Hawaii <- state[as.character(state@data$STATE_NAME) %in% mystates, ]

#crs(Hawaii) <- crs(tiny_adf)
 Hawaii <- projectRaster(tiny_adf,Hawaii, res(tiny_adf), crs(tiny_adf))
 Hawaii <- rgdal::spTRansform(Hawaii, crs(tiny_adf))
subset_h <- crop(tiny_adf, extent(Hawaii))
```
Reading in a small raster file that should be in the extent of ecoregions. Tried to eye-ball getting it to be on boarder of both ecoregions. Might not be. 

```{r}
florida_patch <- raster::raster("~/Downloads/LANDFIRE/Florida_both_83_and_85_US_DIST2014/US_DIST2014\\US_DIST2014.tif")
#florida_patch <- raster(florida_patch)

eco_II<- rgdal::readOGR("~/Documents/work/na_cec_eco_l2/NA_CEC_Eco_Level2.shp")


Southern_coastal_plains <- eco_II[eco_II$NA_L2NAME == "MISSISSIPPI ALLUVIAL AND SOUTHEAST USA COASTAL PLAINS", ]
#plot(Southern_coastal_plains)

Southern_coastal_plains <- raster::spTransform(Southern_coastal_plains, crs(florida_patch))
crs(Southern_coastal_plains) <- crs(florida_patch)



croped <- crop(florida_patch, extent(Southern_coastal_plains))
masked <- mask(florida_patch, mask = Southern_coastal_plains, inverse=TRUE)

writeRaster(masked, "~/Downloads/LANDFIRE/croped_florida_8_5.tif")



```
